aliases:
  icl: issue close
  icr: issue create
  il: issue list
  ire: issue reopen
  iv: issue view
  ivw: issue view --web
  pck: pr checks
  pcl: pr close
  pco: pr checkout
  pcr: pr create
  pd: pr diff
  pl: pr list
  pm: pr merge
  pre: pr reopen
  pv: pr view
  pvw: pr view --web
  rcl: repo clone
  rcr: repo create
  rfk: repo fork --clone --remote
  rv: repo view
  rvw: repo view --web
editor: ''
git_protocol: ssh
