# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

set --prepend fish_function_path /nix/store/shg5yqdgrj223g3zv7052l648cw2jbcq-fishplugin-foreign-env-unstable-2020-02-09/share/fish/vendor_functions.d
fenv source /etc/profiles/per-user/dominikb1888/etc/profile.d/hm-session-vars.sh >/dev/null
set -e fish_function_path[1]

set -U fish_term24bit 1
set-background-to-macOS

/nix/store/qf3sp6yqccvj3vrscjf66q59aw4sr0cz-zoxide-0.8.3/bin/zoxide init fish | source


status --is-login; and begin

    # Login shell initialisation


end

status --is-interactive; and begin

    # Abbreviations


    # Aliases
    alias .. 'cd ..'
    alias :q exit
    alias cat '/nix/store/ydyq9wnfjnmqi594y377z6hpy9yrfxdc-bat-0.22.1/bin/bat'
    alias cl clear
    alias drb 'darwin-rebuild build --flake /Users/dominikb1888/.config/nixpkgs'
    alias drs 'darwin-rebuild switch --flake /Users/dominikb1888/.config/nixpkgs'
    alias du '/nix/store/3qi78qgdg68w5r17ax8nw09ba9jcr6md-du-dust-0.8.3/bin/dust'
    alias flakeup 'nix flake update /Users/dominikb1888/.config/nixpkgs'
    alias fzd fdFzf
    alias g '/nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/bin/git'
    alias h __select_from_last
    alias la 'll -a'
    alias lg 'la --git-ignore'
    alias ll 'ls -l --time-style=iso --icons --git --no-filesize --no-user --header'
    alias ls '/nix/store/xwlzc8l23ckls2cjgavh5d8cgcgd2qv8-exa-0.10.1/bin/exa -1 --group-directories-first'
    alias nb 'nix build'
    alias nd 'nix develop'
    alias nf 'nix flake'
    alias ngf nvimGoToFiles
    alias ngl nvimGoToLine
    alias nr 'nix run'
    alias ns 'nix search'
    alias tb toggle-background
    alias v vim
    alias vi vim
    alias vim nvim

    # Interactive shell intialisation
    # START programs.neovim.extras config ----------------------------------------------------------

    # If shell is running in a Neovim terminal buffer, set the PWD of the buffer to `$PWD`.
    if test -n "$NVIM"
        nvim-sync-term-buffer-pwd
    end

    # Neovim Remote aliases
    if test -n "$NVIM"
        alias n "/nix/store/yyfwy71dk8nnh4p0y1sxjvagxvgng5xg-neovim-remote-2.5.1/bin/nvr"
        alias ns "/nix/store/yyfwy71dk8nnh4p0y1sxjvagxvgng5xg-neovim-remote-2.5.1/bin/nvr -o"
        alias nv "/nix/store/yyfwy71dk8nnh4p0y1sxjvagxvgng5xg-neovim-remote-2.5.1/bin/nvr -O"
        alias nt "/nix/store/yyfwy71dk8nnh4p0y1sxjvagxvgng5xg-neovim-remote-2.5.1/bin/nvr --remote-tab"
        alias neovim "command nvim"
        alias nvim "echo 'This shell is running in a Neovim termainal buffer. Use \'neovim\' to a nested instance of Neovim, otherwise use n, ns, nv, or nt to open files in the this Neovim instance.'"
    else
        alias n nvim
    end

    # END programs.neovim.extras config ------------------------------------------------------------

    # Set term colors based on value of `$term_backdround` when shell starts up.
    set-term-colors

    set -g fish_greeting ""
    # /nix/store/axi68m87is3c32l0bi2ddsxq4rgdwkyw-thefuck-3.32/bin/thefuck --alias | source

    # Run function to set colors that are dependant on `$term_background` and to register them so
    # they are triggerd when the relevent event happens or variable changes.
    set-shell-colors

    # Set Fish colors that aren't dependant the `$term_background`.
    set -g fish_color_quote cyan # color of commands
    set -g fish_color_redirection brmagenta # color of IO redirections
    set -g fish_color_end blue # color of process separators like ';' and '&'
    set -g fish_color_error red # color of potential errors
    set -g fish_color_match --reverse # color of highlighted matching parenthesis
    set -g fish_color_search_match --background=yellow
    set -g fish_color_selection --reverse # color of selected text (vi mode)
    set -g fish_color_operator green # color of parameter expansion operators like '*' and '~'
    set -g fish_color_escape red # color of character escapes like '\n' and and '\x70'
    set -g fish_color_cancel red # color of the '^C' indicator on a canceled command

    set -x FZF_DEFAULT_OPTS '--prompt="🔭 " --height 80% --layout=reverse --border'
    set -x FZF_DEFAULT_COMMAND 'rg --files --no-ignore --hidden --follow --glob "!.git/" --glob "!node_modules/" --glob "!vendor/" --glob "!undo/" --glob "!plugged/"'
    # set -x BAT_THEME 'gruvbox-dark'

    export EXA_ICON_SPACING=2

    if test "$TERM" != dumb -a \( -z "$INSIDE_EMACS" -o "$INSIDE_EMACS" = vterm \)
        eval (/etc/profiles/per-user/dominikb1888/bin/starship init fish)
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/dominikb1888/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/166vbqxg5gvxk3996f5cmccsmjdn376v-direnv-2.32.2/bin/direnv hook fish | source


end
