# abduco
# Autogenerated from man page /nix/store/b1f4r6jqdgbdsdlacbbhr7ph3d7gw7rc-abduco-2020-04-30/share/man/man1/abduco.1.gz
complete -c abduco -s a -d 'Attach to an existing session'
complete -c abduco -s A -d 'Try to connect to an existing session, upon failure create said session and a…'
complete -c abduco -s c -d 'Create a new session and attach immediately to it'
complete -c abduco -s n -d 'Create a new session but do not attach to it'
complete -c abduco -s e -d 'Set the key to detach.  Defaults to Ctrl+\\e which is specified as ^\\\\ i. e'
complete -c abduco -s f -d 'Force creation of session when there is an already terminated session of the …'
complete -c abduco -s l -d 'Attach with the lowest priority, meaning this client will be the last to cont…'
complete -c abduco -s p -d 'Pass through content of standard input to the session'
complete -c abduco -s q -d 'Be quiet, do not print informative messages'
complete -c abduco -s r -d 'Read-only session, user input is ignored'
complete -c abduco -s v -d 'Print version information and exit'

