# gh-alias-set
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-alias-set.1.gz
complete -c gh-alias-set -s s -l shell -d 'Declare an alias to be passed through a shell interpreter EXAMPLE # note: Com…'

