# gh-auth-status
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-auth-status.1.gz
complete -c gh-auth-status -s h -l hostname -d 'Check a specific hostname\'s auth status'
complete -c gh-auth-status -s t -l show-token -d 'Display the auth token SEE ALSO'

