# gh-auth-login
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-auth-login.1.gz
complete -c gh-auth-login -s p -l git-protocol -d 'The protocol to use for git operations: {ssh|https}'
complete -c gh-auth-login -s h -l hostname -d 'The hostname of the GitHub instance to authenticate with'
complete -c gh-auth-login -s s -l scopes -d 'Additional authentication scopes to request'
complete -c gh-auth-login -s w -l web -d 'Open a browser to authenticate'
complete -c gh-auth-login -l with-token -d 'Read token from standard input EXAMPLE # start interactive setup $ gh auth lo…'

