# gh-auth-logout
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-auth-logout.1.gz
complete -c gh-auth-logout -s h -l hostname -d 'The hostname of the GitHub instance to log out of EXAMPLE $ gh auth logout # …'

