# gh-auth-setup-git
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-auth-setup-git.1.gz
complete -c gh-auth-setup-git -s h -l hostname -d 'The hostname to configure git for SEE ALSO'

