# gh-auth-refresh
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-auth-refresh.1.gz
complete -c gh-auth-refresh -s h -l hostname -d 'The GitHub host to use for authentication'
complete -c gh-auth-refresh -s s -l scopes -d 'Additional authentication scopes for gh to have EXAMPLE $ gh auth refresh --s…'

