# gh-api
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-api.1.gz
complete -c gh-api -l field -d 'request method to POST'
complete -c gh-api -l method -d 'The -F/--field flag has magic type conversion based on the format of the valu…'
complete -c gh-api -l cache -d 'Cache the response, e. g.  "3600s", "60m", "1h"'
complete -c gh-api -s F -d 'Add a typed parameter in key=value format'
complete -c gh-api -s H -l header -d 'Add a HTTP request header in key:value format'
complete -c gh-api -l hostname -d 'The GitHub hostname for the request (default "github. com")'
complete -c gh-api -s i -l include -d 'Include HTTP response status line and headers in the output'
complete -c gh-api -l input -d 'The file to use as body for the HTTP request (use "-" to read from standard i…'
complete -c gh-api -s q -l jq -d 'Query to select values from the response using jq syntax'
complete -c gh-api -s X -d 'The HTTP method for the request'
complete -c gh-api -l paginate -d 'Make additional HTTP requests to fetch all pages of results'
complete -c gh-api -s p -l preview -d 'GitHub API preview names to request (without the "-preview" suffix)'
complete -c gh-api -s f -l raw-field -d 'Add a string parameter in key=value format'
complete -c gh-api -l silent -d 'Do not print the response body'
complete -c gh-api -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" EXAMPLE # li…'

