# gh-browse
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-browse.1.gz
complete -c gh-browse -s b -l branch -d 'Select another branch by passing in the branch name'
complete -c gh-browse -s c -l commit -d 'Open the last commit'
complete -c gh-browse -s n -l no-browser -d 'Print destination URL instead of opening the browser'
complete -c gh-browse -s p -l projects -d 'Open repository projects'
complete -c gh-browse -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format'
complete -c gh-browse -s s -l settings -d 'Open repository settings'
complete -c gh-browse -s w -l wiki -d 'Open repository wiki EXAMPLE $ gh browse #=> Open the home page of the curren…'

