# gh-codespace-edit
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-codespace-edit.1.gz
complete -c gh-codespace-edit -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-edit -s d -l display-name -d 'Set the display name'
complete -c gh-codespace-edit -s m -l machine -d 'Set hardware specifications for the VM SEE ALSO'

