# gh-config-get
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-config-get.1.gz
complete -c gh-config-get -s h -l host -d 'Get per-host setting EXAMPLE $ gh config get git_protocol https SEE ALSO'

