# gh-codespace-stop
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-codespace-stop.1.gz
complete -c gh-codespace-stop -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-stop -s o -l org -d 'The login handle of the organization (admin-only)'
complete -c gh-codespace-stop -s u -l user -d 'The username to stop codespace for (used with --org) SEE ALSO'

