# gh-codespace-rebuild
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-codespace-rebuild.1.gz
complete -c gh-codespace-rebuild -s c -l codespace -d 'name of the codespace'
complete -c gh-codespace-rebuild -l full -d 'perform a full rebuild SEE ALSO'

