# gh-codespace-list
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-codespace-list.1.gz
complete -c gh-codespace-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-codespace-list -l json -d 'Output JSON with the specified fields'
complete -c gh-codespace-list -s L -l limit -d 'Maximum number of codespaces to list'
complete -c gh-codespace-list -s o -l org -d 'The login handle of the organization to list codespaces for (admin-only)'
complete -c gh-codespace-list -s r -l repo -d 'Repository name with owner: user/repo'
complete -c gh-codespace-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-codespace-list -s u -l user -d 'The username to list codespaces for (used with --org) SEE ALSO'

