# gh-codespace-create
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-codespace-create.1.gz
complete -c gh-codespace-create -s b -l branch -d 'repository branch'
complete -c gh-codespace-create -l default-permissions -d 'do not prompt to accept additional permissions requested by the codespace'
complete -c gh-codespace-create -l devcontainer-path -d 'path to the devcontainer. json file to use when creating codespace'
complete -c gh-codespace-create -l idle-timeout -d 'allowed inactivity before codespace is stopped, e. g.  "10m", "1h"'
complete -c gh-codespace-create -s l -l location -d 'location: {EastUs|SouthEastAsia|WestEurope|WestUs2} (determined automatically…'
complete -c gh-codespace-create -s m -l machine -d 'hardware specifications for the VM'
complete -c gh-codespace-create -s r -l repo -d 'repository name with owner: user/repo'
complete -c gh-codespace-create -l retention-period -d 'allowed time after shutting down before the codespace is automatically delete…'
complete -c gh-codespace-create -s s -l status -d 'show status of post-create command and dotfiles SEE ALSO'

