# gh-codespace-ports
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-codespace-ports.1.gz
complete -c gh-codespace-ports -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-ports -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-codespace-ports -l json -d 'Output JSON with the specified fields'
complete -c gh-codespace-ports -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" SEE ALSO'

