# gh-codespace-jupyter
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-codespace-jupyter.1.gz
complete -c gh-codespace-jupyter -s c -l codespace -d 'Name of the codespace SEE ALSO'

