# gh-codespace-code
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-codespace-code.1.gz
complete -c gh-codespace-code -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-code -l insiders -d 'Use the insiders version of Visual Studio Code'
complete -c gh-codespace-code -s w -l web -d 'Use the web version of Visual Studio Code SEE ALSO'

