# gh-codespace-ports-visibility
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-codespace-ports-visibility.1.gz
complete -c gh-codespace-ports-visibility -s c -l codespace -d 'Name of the codespace EXAMPLE gh codespace ports visibility 80:org 3000:priva…'

