# gh-config-set
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-config-set.1.gz
complete -c gh-config-set -s h -l host -d 'Set per-host setting EXAMPLE $ gh config set editor vim $ gh config set edito…'

