# gh-extension-upgrade
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-extension-upgrade.1.gz
complete -c gh-extension-upgrade -l all -d 'Upgrade all extensions'
complete -c gh-extension-upgrade -l dry-run -d 'Only display upgrades'
complete -c gh-extension-upgrade -l force -d 'Force upgrade extension SEE ALSO'

