# gh-extension-browse
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-extension-browse.1.gz
complete -c gh-extension-browse -l debug -d 'log to /tmp/extBrowse-* SEE ALSO'

