# gh-extension-install
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-extension-install.1.gz
complete -c gh-extension-install -l pin -d 'pin extension to a release tag or commit ref EXAMPLE $ gh extension install o…'

