# gh-extension-search
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-extension-search.1.gz
complete -c gh-extension-search -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-extension-search -l json -d 'Output JSON with the specified fields'
complete -c gh-extension-search -l license -d 'Filter based on license type'
complete -c gh-extension-search -s L -l limit -d 'Maximum number of extensions to fetch'
complete -c gh-extension-search -l order -d 'Order of repositories returned, ignored unless \'--sort\' flag is specified: {a…'
complete -c gh-extension-search -l owner -d 'Filter on owner'
complete -c gh-extension-search -l sort -d 'Sort fetched repositories: {forks|help-wanted-issues|stars|updated}'
complete -c gh-extension-search -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-extension-search -s w -l web -d 'Open the search query in the web browser EXAMPLE # List the first 30 extensio…'

