# gh-extension-create
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-extension-create.1.gz
complete -c gh-extension-create -l precompiled -d 'Create a precompiled extension'

