# gh-gist-list
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-gist-list.1.gz
complete -c gh-gist-list -s L -l limit -d 'Maximum number of gists to fetch'
complete -c gh-gist-list -l public -d 'Show only public gists'
complete -c gh-gist-list -l secret -d 'Show only secret gists SEE ALSO'

