# gh-gist-view
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-gist-view.1.gz
complete -c gh-gist-view -s f -l filename -d 'Display a single file from the gist'
complete -c gh-gist-view -l files -d 'List file names from the gist'
complete -c gh-gist-view -s r -l raw -d 'Print raw instead of rendered gist contents'
complete -c gh-gist-view -s w -l web -d 'Open gist in the browser SEE ALSO'

