# gh-gist-create
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-gist-create.1.gz
complete -c gh-gist-create -s d -l desc -d 'A description for this gist'
complete -c gh-gist-create -s f -l filename -d 'Provide a filename to be used when reading from standard input'
complete -c gh-gist-create -s p -l public -d 'List the gist publicly (default: secret)'
complete -c gh-gist-create -s w -l web -d 'Open the web browser with created gist EXAMPLE # publish file \'hello'

