# gh-gist-edit
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-gist-edit.1.gz
complete -c gh-gist-edit -s a -l add -d 'Add a new file to the gist'
complete -c gh-gist-edit -s d -l desc -d 'New description for the gist'
complete -c gh-gist-edit -s f -l filename -d 'Select a file to edit SEE ALSO'

