# gh-issue-create
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-issue-create.1.gz
complete -c gh-issue-create -s a -l assignee -d 'Assign people by their login.  Use "@me" to self-assign'
complete -c gh-issue-create -s b -l body -d 'Supply a body.  Will prompt for one otherwise'
complete -c gh-issue-create -s F -l body-file -d 'Read body text from file (use "-" to read from standard input)'
complete -c gh-issue-create -s l -l label -d 'Add labels by name'
complete -c gh-issue-create -s m -l milestone -d 'Add the issue to a milestone by name'
complete -c gh-issue-create -s p -l project -d 'Add the issue to projects by name'
complete -c gh-issue-create -l recover -d 'Recover input from a failed run of create'
complete -c gh-issue-create -s t -l title -d 'Supply a title.  Will prompt for one otherwise'
complete -c gh-issue-create -s w -l web -d 'Open the browser to create an issue OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-issue-create -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh iss…'

