# gh-issue-close
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-issue-close.1.gz
complete -c gh-issue-close -s c -l comment -d 'Leave a closing comment'
complete -c gh-issue-close -s r -l reason -d 'Reason for closing: {completed|not planned} OPTIONS INHERITED FROM PARENT COM…'
complete -c gh-issue-close -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

