# gh-issue-develop
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-issue-develop.1.gz
complete -c gh-issue-develop -s b -l base -d 'Name of the base branch you want to make your new branch from'
complete -c gh-issue-develop -s c -l checkout -d 'Checkout the branch after creating it'
complete -c gh-issue-develop -s i -l issue-repo -d 'Name or URL of the issue\'s repository'
complete -c gh-issue-develop -s l -l list -d 'List linked branches for the issue'
complete -c gh-issue-develop -s n -l name -d 'Name of the branch to create OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-issue-develop -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh iss…'

