# gh-issue-edit
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-issue-edit.1.gz
complete -c gh-issue-edit -l add-assignee -d 'Add assigned users by their login.  Use "@me" to assign yourself'
complete -c gh-issue-edit -l add-label -d 'Add labels by name'
complete -c gh-issue-edit -l add-project -d 'Add the issue to projects by name'
complete -c gh-issue-edit -s b -l body -d 'Set the new body'
complete -c gh-issue-edit -s F -l body-file -d 'Read body text from file (use "-" to read from standard input)'
complete -c gh-issue-edit -s m -l milestone -d 'Edit the milestone the issue belongs to by name'
complete -c gh-issue-edit -l remove-assignee -d 'Remove assigned users by their login.  Use "@me" to unassign yourself'
complete -c gh-issue-edit -l remove-label -d 'Remove labels by name'
complete -c gh-issue-edit -l remove-project -d 'Remove the issue from projects by name'
complete -c gh-issue-edit -s t -l title -d 'Set the new title.  OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-issue-edit -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh iss…'

