# gh-label
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-label.1.gz
complete -c gh-label -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

