# gh-label-clone
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-label-clone.1.gz
complete -c gh-label-clone -s f -l force -d 'Overwrite labels in the destination repository OPTIONS INHERITED FROM PARENT …'
complete -c gh-label-clone -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # clone …'

