# gh-label-create
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-label-create.1.gz
complete -c gh-label-create -s c -l color -d 'Color of the label'
complete -c gh-label-create -s d -l description -d 'Description of the label'
complete -c gh-label-create -s f -l force -d 'Update the label color and description if label already exists OPTIONS INHERI…'
complete -c gh-label-create -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # create…'

