# gh-label-list
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-label-list.1.gz
complete -c gh-label-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-label-list -l json -d 'Output JSON with the specified fields'
complete -c gh-label-list -s L -l limit -d 'Maximum number of labels to fetch'
complete -c gh-label-list -l order -d 'Order of labels returned: {asc|desc}'
complete -c gh-label-list -s S -l search -d 'Search label names and descriptions'
complete -c gh-label-list -l sort -d 'Sort fetched labels: {created|name}'
complete -c gh-label-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-label-list -s w -l web -d 'List labels in the web browser OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-label-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # sort l…'

