# gh-pr-create
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-create.1.gz
complete -c gh-pr-create -s a -l assignee -d 'Assign people by their login.  Use "@me" to self-assign'
complete -c gh-pr-create -s B -l base -d 'The branch into which you want your code merged'
complete -c gh-pr-create -s b -l body -d 'Body for the pull request'
complete -c gh-pr-create -s F -l body-file -d 'Read body text from file (use "-" to read from standard input)'
complete -c gh-pr-create -s d -l draft -d 'Mark pull request as a draft'
complete -c gh-pr-create -s f -l fill -d 'Do not prompt for title/body and just use commit info'
complete -c gh-pr-create -s H -l head -d 'The branch that contains commits for your pull request (default: current bran…'
complete -c gh-pr-create -s l -l label -d 'Add labels by name'
complete -c gh-pr-create -s m -l milestone -d 'Add the pull request to a milestone by name'
complete -c gh-pr-create -l no-maintainer-edit -d 'Disable maintainer\'s ability to modify pull request'
complete -c gh-pr-create -s p -l project -d 'Add the pull request to projects by name'
complete -c gh-pr-create -l recover -d 'Recover input from a failed run of create'
complete -c gh-pr-create -s r -l reviewer -d 'Request reviews from people or teams by their handle'
complete -c gh-pr-create -s t -l title -d 'Title for the pull request'
complete -c gh-pr-create -s w -l web -d 'Open the web browser to create a pull request OPTIONS INHERITED FROM PARENT C…'
complete -c gh-pr-create -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh pr …'

