# gh-pr-close
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-close.1.gz
complete -c gh-pr-close -s c -l comment -d 'Leave a closing comment'
complete -c gh-pr-close -s d -l delete-branch -d 'Delete the local and remote branch after close OPTIONS INHERITED FROM PARENT …'
complete -c gh-pr-close -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

