# gh-pr-ready
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-ready.1.gz
complete -c gh-pr-ready -l undo -d 'Convert a pull request to "draft" OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-ready -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

