# gh-pr-view
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-view.1.gz
complete -c gh-pr-view -s c -l comments -d 'View pull request comments'
complete -c gh-pr-view -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-pr-view -l json -d 'Output JSON with the specified fields'
complete -c gh-pr-view -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-pr-view -s w -l web -d 'Open a pull request in the browser OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-view -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

