# gh-pr-checkout
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-checkout.1.gz
complete -c gh-pr-checkout -s b -l branch -d 'Local branch name to use (default: the name of the head branch)'
complete -c gh-pr-checkout -l detach -d 'Checkout PR with a detached HEAD'
complete -c gh-pr-checkout -s f -l force -d 'Reset the existing local branch to the latest state of the pull request'
complete -c gh-pr-checkout -l recurse-submodules -d 'Update all submodules after checkout OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-checkout -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

