# gh-pr-edit
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-edit.1.gz
complete -c gh-pr-edit -l add-assignee -d 'Add assigned users by their login.  Use "@me" to assign yourself'
complete -c gh-pr-edit -l add-label -d 'Add labels by name'
complete -c gh-pr-edit -l add-project -d 'Add the pull request to projects by name'
complete -c gh-pr-edit -l add-reviewer -d 'Add reviewers by their login'
complete -c gh-pr-edit -s B -l base -d 'Change the base branch for this pull request'
complete -c gh-pr-edit -s b -l body -d 'Set the new body'
complete -c gh-pr-edit -s F -l body-file -d 'Read body text from file (use "-" to read from standard input)'
complete -c gh-pr-edit -s m -l milestone -d 'Edit the milestone the pull request belongs to by name'
complete -c gh-pr-edit -l remove-assignee -d 'Remove assigned users by their login.  Use "@me" to unassign yourself'
complete -c gh-pr-edit -l remove-label -d 'Remove labels by name'
complete -c gh-pr-edit -l remove-project -d 'Remove the pull request from projects by name'
complete -c gh-pr-edit -l remove-reviewer -d 'Remove reviewers by their login'
complete -c gh-pr-edit -s t -l title -d 'Set the new title.  OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-edit -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh pr …'

