# gh-pr-diff
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-diff.1.gz
complete -c gh-pr-diff -l color -d 'Use color in diff output: {always|never|auto}'
complete -c gh-pr-diff -l name-only -d 'Display only names of changed files'
complete -c gh-pr-diff -l patch -d 'Display diff in patch format'
complete -c gh-pr-diff -s w -l web -d 'Open the pull request diff in the browser OPTIONS INHERITED FROM PARENT COMMA…'
complete -c gh-pr-diff -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

