# gh-pr-comment
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-comment.1.gz
complete -c gh-pr-comment -s b -l body -d 'The comment body text'
complete -c gh-pr-comment -s F -l body-file -d 'Read body text from file (use "-" to read from standard input)'
complete -c gh-pr-comment -l edit-last -d 'Edit the last comment of the same author'
complete -c gh-pr-comment -s e -l editor -d 'Skip prompts and open the text editor to write the body in'
complete -c gh-pr-comment -s w -l web -d 'Open the web browser to write the comment OPTIONS INHERITED FROM PARENT COMMA…'
complete -c gh-pr-comment -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh pr …'

