# gh-pr-checks
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-checks.1.gz
complete -c gh-pr-checks -s i -l interval -d 'Refresh interval in seconds when using --watch flag'
complete -c gh-pr-checks -l required -d 'Only show checks that are required'
complete -c gh-pr-checks -l watch -d 'Watch checks until they finish'
complete -c gh-pr-checks -s w -l web -d 'Open the web browser to show details about checks OPTIONS INHERITED FROM PARE…'
complete -c gh-pr-checks -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

