# gh-pr-review
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-pr-review.1.gz
complete -c gh-pr-review -s a -l approve -d 'Approve pull request'
complete -c gh-pr-review -s b -l body -d 'Specify the body of a review'
complete -c gh-pr-review -s F -l body-file -d 'Read body text from file (use "-" to read from standard input)'
complete -c gh-pr-review -s c -l comment -d 'Comment on a pull request'
complete -c gh-pr-review -s r -l request-changes -d 'Request changes on a pull request OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-review -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # approv…'

