# gh-repo-sync
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-repo-sync.1.gz
complete -c gh-repo-sync -l force -d 'by synced using a hard reset'
complete -c gh-repo-sync -s b -l branch -d 'Branch to sync (default: main branch)'
complete -c gh-repo-sync -s s -l source -d 'Source repository EXAMPLE # Sync local repository from remote parent $ gh rep…'

