# gh-repo-edit
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-repo-edit.1.gz
complete -c gh-repo-edit -l add-topic -d 'Add repository topic'
complete -c gh-repo-edit -l allow-forking -d 'Allow forking of an organization repository'
complete -c gh-repo-edit -l default-branch -d 'Set the default branch name for the repository'
complete -c gh-repo-edit -l delete-branch-on-merge -d 'Delete head branch when pull requests are merged'
complete -c gh-repo-edit -s d -l description -d 'Description of the repository'
complete -c gh-repo-edit -l enable-auto-merge -d 'Enable auto-merge functionality'
complete -c gh-repo-edit -l enable-issues -d 'Enable issues in the repository'
complete -c gh-repo-edit -l enable-merge-commit -d 'Enable merging pull requests via merge commit'
complete -c gh-repo-edit -l enable-projects -d 'Enable projects in the repository'
complete -c gh-repo-edit -l enable-rebase-merge -d 'Enable merging pull requests via rebase'
complete -c gh-repo-edit -l enable-squash-merge -d 'Enable merging pull requests via squashed commit'
complete -c gh-repo-edit -l enable-wiki -d 'Enable wiki in the repository'
complete -c gh-repo-edit -s h -l homepage -d 'Repository home page URL'
complete -c gh-repo-edit -l remove-topic -d 'Remove repository topic'
complete -c gh-repo-edit -l template -d 'Make the repository available as a template repository'
complete -c gh-repo-edit -l visibility -d 'Change the visibility of the repository to {public,private,internal} EXAMPLE …'

