# gh-run-list
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-run-list.1.gz
complete -c gh-run-list -s b -l branch -d 'Filter runs by branch'
complete -c gh-run-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-run-list -l json -d 'Output JSON with the specified fields'
complete -c gh-run-list -s L -l limit -d 'Maximum number of runs to fetch'
complete -c gh-run-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-run-list -s u -l user -d 'Filter runs by user who triggered the run'
complete -c gh-run-list -s w -l workflow -d 'Filter runs by workflow OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-run-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

