# gh-release-download
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-release-download.1.gz
complete -c gh-release-download -s A -l archive -d 'Download the source code archive in the specified format (zip or tar. gz)'
complete -c gh-release-download -l clobber -d 'Overwrite existing files of the same name'
complete -c gh-release-download -s D -l dir -d 'The directory to download files into'
complete -c gh-release-download -s O -l output -d 'The file to write a single asset to (use "-" to write to standard output)'
complete -c gh-release-download -s p -l pattern -d 'Download only assets that match a glob pattern'
complete -c gh-release-download -l skip-existing -d 'Skip downloading when files of the same name exist OPTIONS INHERITED FROM PAR…'
complete -c gh-release-download -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # downlo…'

