# gh-release-delete
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-release-delete.1.gz
complete -c gh-release-delete -l cleanup-tag -d 'Delete the specified tag in addition to its release'
complete -c gh-release-delete -s y -l yes -d 'Skip the confirmation prompt OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-release-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

