# gh-release-edit
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-release-edit.1.gz
complete -c gh-release-edit -l discussion-category -d 'Start a discussion in the specified category when publishing a draft'
complete -c gh-release-edit -l draft -d 'Save the release as a draft instead of publishing it'
complete -c gh-release-edit -l latest -d 'Explicitly mark the release as "Latest"'
complete -c gh-release-edit -s n -l notes -d 'Release notes'
complete -c gh-release-edit -s F -l notes-file -d 'Read release notes from file (use "-" to read from standard input)'
complete -c gh-release-edit -l prerelease -d 'Mark the release as a prerelease'
complete -c gh-release-edit -l tag -d 'The name of the tag'
complete -c gh-release-edit -l target -d 'Target branch or full commit SHA (default: main branch)'
complete -c gh-release-edit -s t -l title -d 'Release title OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-release-edit -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE Publish …'

