# gh-repo-fork
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-repo-fork.1.gz
complete -c gh-repo-fork -l clone -d 'Clone the fork'
complete -c gh-repo-fork -l fork-name -d 'Rename the forked repository'
complete -c gh-repo-fork -l org -d 'Create the fork in an organization'
complete -c gh-repo-fork -l remote -d 'Add a git remote for the fork'
complete -c gh-repo-fork -l remote-name -d 'Specify the name for the new remote SEE ALSO'

