# gh-repo-deploy-key-list
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-repo-deploy-key-list.1.gz
complete -c gh-repo-deploy-key-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

