# gh-repo-deploy-key-add
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-repo-deploy-key-add.1.gz
complete -c gh-repo-deploy-key-add -s w -l allow-write -d 'Allow write access for the key'
complete -c gh-repo-deploy-key-add -s t -l title -d 'Title of the new key OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-repo-deploy-key-add -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # genera…'

