# gh-repo-list
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-repo-list.1.gz
complete -c gh-repo-list -l archived -d 'Show only archived repositories'
complete -c gh-repo-list -l fork -d 'Show only forks'
complete -c gh-repo-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-repo-list -l json -d 'Output JSON with the specified fields'
complete -c gh-repo-list -s l -l language -d 'Filter by primary coding language'
complete -c gh-repo-list -s L -l limit -d 'Maximum number of repositories to list'
complete -c gh-repo-list -l no-archived -d 'Omit archived repositories'
complete -c gh-repo-list -l source -d 'Show only non-forks'
complete -c gh-repo-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-repo-list -l topic -d 'Filter by topic'
complete -c gh-repo-list -l visibility -d 'Filter by repository visibility: {public|private|internal} SEE ALSO'

