# gh-run-download
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-run-download.1.gz
complete -c gh-run-download -s D -l dir -d 'The directory to download artifacts into'
complete -c gh-run-download -s n -l name -d 'Download artifacts that match any of the given names'
complete -c gh-run-download -s p -l pattern -d 'Download artifacts that match a glob pattern OPTIONS INHERITED FROM PARENT CO…'
complete -c gh-run-download -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Downlo…'

