# gh-release-list
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-release-list.1.gz
complete -c gh-release-list -l exclude-drafts -d 'Exclude draft releases'
complete -c gh-release-list -s L -l limit -d 'Maximum number of items to fetch OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-release-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

