# gh-run-watch
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-run-watch.1.gz
complete -c gh-run-watch -l exit-status -d 'Exit with non-zero status if run fails'
complete -c gh-run-watch -s i -l interval -d 'Refresh interval in seconds OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-run-watch -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Watch …'

