# gh-ssh-key-delete
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-ssh-key-delete.1.gz
complete -c gh-ssh-key-delete -s y -l confirm -d 'Skip the confirmation prompt SEE ALSO'

