# gh-status
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-status.1.gz
complete -c gh-status -s e -l exclude -d 'Comma separated list of repos to exclude in owner/name format'
complete -c gh-status -s o -l org -d 'Report status within an organization EXAMPLE $ gh status -e cli/cli -e cli/go…'

