# gh-secret-list
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-secret-list.1.gz
complete -c gh-secret-list -s a -l app -d 'List secrets for a specific application: {actions|codespaces|dependabot}'
complete -c gh-secret-list -s e -l env -d 'List secrets for an environment'
complete -c gh-secret-list -s o -l org -d 'List secrets for an organization'
complete -c gh-secret-list -s u -l user -d 'List a secret for your user OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-secret-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

