# gh-secret-delete
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-secret-delete.1.gz
complete -c gh-secret-delete -s a -l app -d 'Delete a secret for a specific application: {actions|codespaces|dependabot}'
complete -c gh-secret-delete -s e -l env -d 'Delete a secret for an environment'
complete -c gh-secret-delete -s o -l org -d 'Delete a secret for an organization'
complete -c gh-secret-delete -s u -l user -d 'Delete a secret for your user OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-secret-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

