# gh-secret-set
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-secret-set.1.gz
complete -c gh-secret-set -s a -l app -d 'Set the application for a secret: {actions|codespaces|dependabot}'
complete -c gh-secret-set -s b -l body -d 'The value for the secret (reads from standard input if not specified)'
complete -c gh-secret-set -s e -l env -d 'Set deployment environment secret'
complete -c gh-secret-set -s f -l env-file -d 'Load secret names and values from a dotenv-formatted file'
complete -c gh-secret-set -l no-store -d 'Print the encrypted, base64-encoded value instead of storing it on Github'
complete -c gh-secret-set -s o -l org -d 'Set organization secret'
complete -c gh-secret-set -s r -l repos -d 'List of repositories that can access an organization or user secret'
complete -c gh-secret-set -s u -l user -d 'Set a secret for your user'
complete -c gh-secret-set -s v -l visibility -d 'Set visibility for an organization secret: {all|private|selected} OPTIONS INH…'
complete -c gh-secret-set -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Paste …'

