# gh-ssh-key-add
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-ssh-key-add.1.gz
complete -c gh-ssh-key-add -s t -l title -d 'Title for the new key SEE ALSO'

