# gh-workflow-view
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-workflow-view.1.gz
complete -c gh-workflow-view -s r -l ref -d 'The branch or tag name which contains the version of the workflow file you\'d …'
complete -c gh-workflow-view -s w -l web -d 'Open workflow in the browser'
complete -c gh-workflow-view -s y -l yaml -d 'View the workflow yaml file OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-workflow-view -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Intera…'

