# gh-workflow-run
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh-workflow-run.1.gz
complete -c gh-workflow-run -s F -l field -d 'Add a string parameter in key=value format, respecting @ syntax'
complete -c gh-workflow-run -l json -d 'Read workflow inputs as JSON via STDIN'
complete -c gh-workflow-run -s f -l raw-field -d 'Add a string parameter in key=value format'
complete -c gh-workflow-run -s r -l ref -d 'The branch or tag name which contains the version of the workflow file you\'d …'
complete -c gh-workflow-run -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Have g…'

