# gh
# Autogenerated from man page /nix/store/2ph1hk79h8xfv70via2075n0lz1my80v-gh-2.20.2/share/man/man1/gh.1.gz
complete -c gh -l version -d 'Show gh version EXAMPLE $ gh issue create $ gh repo clone cli/cli $ gh pr che…'

