# git-lfs-checkout
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-checkout.1.gz
complete -c git-lfs-checkout -l base
complete -c git-lfs-checkout -l ours
complete -c git-lfs-checkout -l theirs
complete -c git-lfs-checkout -l to

