# git-write-tree
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-write-tree.1.gz
complete -c git-write-tree -l missing-ok -d 'Normally git write-tree ensures that the objects referenced by the directory …'
complete -c git-write-tree -l prefix -d 'Writes a tree object that represents a subdirectory <prefix>'

