# git-count-objects
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-count-objects.1.gz
complete -c git-count-objects -s v -l verbose -d 'Report in more detail: . sp count: the number of loose objects '
complete -c git-count-objects -s H -l human-readable -d 'Print sizes in human readable format'

