# git-lfs-merge-driver
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-merge-driver.1.gz
complete -c git-lfs-merge-driver -l ancestor
complete -c git-lfs-merge-driver -l current
complete -c git-lfs-merge-driver -l marker-size
complete -c git-lfs-merge-driver -l other
complete -c git-lfs-merge-driver -l program

