# git-lfs-pointer
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-pointer.1.gz
complete -c git-lfs-pointer -l file
complete -c git-lfs-pointer -l pointer
complete -c git-lfs-pointer -l stdin
complete -c git-lfs-pointer -l check
complete -c git-lfs-pointer -l strict -l no-strict

