# git-diagnose
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-diagnose.1.gz
complete -c git-diagnose -s o -l output-directory -d 'Place the resulting diagnostics archive in <path> instead of the current dire…'
complete -c git-diagnose -s s -l suffix -d 'Specify an alternate suffix for the diagnostics archive name, to create a fil…'
complete -c git-diagnose -l mode -d 'Specify the type of diagnostics that should be collected'

