# git-lfs-pull
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-pull.1.gz
complete -c git-lfs-pull -s I -l include
complete -c git-lfs-pull -s X -l exclude

