# git-lfs-update
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-update.1.gz
complete -c git-lfs-update -l manual -s m
complete -c git-lfs-update -l force -s f

