# git-credential-store
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-credential-store.1.gz
complete -c git-credential-store -l file -d 'Use <path> to lookup and store credentials'

