# git-for-each-repo
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-for-each-repo.1.gz
complete -c git-for-each-repo -l config -d 'Use the given config variable as a multi-valued list storing absolute path na…'

