# git-lfs-locks
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-locks.1.gz
complete -c git-lfs-locks -s r -l remote
complete -c git-lfs-locks -s i -l id
complete -c git-lfs-locks -s p -l path
complete -c git-lfs-locks -l local
complete -c git-lfs-locks -l cached
complete -c git-lfs-locks -l verify
complete -c git-lfs-locks -s l -l limit
complete -c git-lfs-locks -l json

