# git-check-mailmap
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-check-mailmap.1.gz
complete -c git-check-mailmap -l stdin -d 'Read contacts, one per line, from the standard input after exhausting contact…'

