# git-verify-commit
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-verify-commit.1.gz
complete -c git-verify-commit -l raw -d 'Print the raw gpg status output to standard error instead of the normal human…'
complete -c git-verify-commit -s v -l verbose -d 'Print the contents of the commit object before validating it'

