# git-lfs-clone
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-clone.1.gz
complete -c git-lfs-clone -s I -l include
complete -c git-lfs-clone -s X -l exclude
complete -c git-lfs-clone -l skip-repo

