# git-pack-redundant
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-pack-redundant.1.gz
complete -c git-pack-redundant -l all -d 'Processes all packs.  Any filenames on the command line are ignored'
complete -c git-pack-redundant -l alt-odb -d 'Don\'t require objects present in packs from alternate object directories to b…'
complete -c git-pack-redundant -l verbose -d 'Outputs some statistics to stderr.  Has a small performance penalty'

