# git-lfs-prune
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-prune.1.gz
complete -c git-lfs-prune -l dry-run -s d
complete -c git-lfs-prune -l force -s f
complete -c git-lfs-prune -l recent
complete -c git-lfs-prune -l verify-remote -s c
complete -c git-lfs-prune -l no-verify-remote
complete -c git-lfs-prune -l verbose -s v

