# git-lfs-ls-files
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-ls-files.1.gz
complete -c git-lfs-ls-files -s l -l long
complete -c git-lfs-ls-files -s s -l size
complete -c git-lfs-ls-files -s d -l debug
complete -c git-lfs-ls-files -s a -l all
complete -c git-lfs-ls-files -l deleted
complete -c git-lfs-ls-files -s I -l include
complete -c git-lfs-ls-files -s X -l exclude
complete -c git-lfs-ls-files -s n -l name-only

