# git-lfs-fsck
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-fsck.1.gz
complete -c git-lfs-fsck -l objects
complete -c git-lfs-fsck -l pointers

