# git-verify-pack
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-verify-pack.1.gz
complete -c git-verify-pack -s v -l verbose -d 'After verifying the pack, show list of objects contained in the pack and a hi…'
complete -c git-verify-pack -s s -l stat-only -d 'Do not verify the pack contents; only show the histogram of delta chain length'

