# git-cherry
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-cherry.1.gz
complete -c git-cherry -s v -d 'Show the commit subjects next to the SHA1s'

