# git-receive-pack
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-receive-pack.1.gz
complete -c git-receive-pack -l http-backend-info-refs -d 'Used by git-http-backend(1) to serve up $GIT_URL/info/refs?service=git-receiv…'

