# git-mktag
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-mktag.1.gz
complete -c git-mktag -l strict -d 'By default mktag turns on the equivalent of git-fsck(1) --strict mode'
complete -c git-mktag -l no-strict -d 'to disable it'

