# git-lfs-migrate
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-migrate.1.gz
complete -c git-lfs-migrate -l everything -d 'satisfactory!) it may be convenient to update multiple branches on your remot…'
complete -c git-lfs-migrate -s I -l include
complete -c git-lfs-migrate -s X -l exclude
complete -c git-lfs-migrate -l include-ref
complete -c git-lfs-migrate -l exclude-ref
complete -c git-lfs-migrate -l skip-fetch
complete -c git-lfs-migrate -l yes
complete -c git-lfs-migrate -l above
complete -c git-lfs-migrate -l top
complete -c git-lfs-migrate -l unit
complete -c git-lfs-migrate -l pointers
complete -c git-lfs-migrate -l fixup
complete -c git-lfs-migrate -l verbose
complete -c git-lfs-migrate -l object-map
complete -c git-lfs-migrate -l no-rewrite
complete -c git-lfs-migrate -s m -l message
complete -c git-lfs-migrate -l remote

