# git-version
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-version.1.gz
complete -c git-version -l build-options -d 'Include additional information about how git was built for diagnostic purposes'

