# git-patch-id
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-patch-id.1.gz
complete -c git-patch-id -l stable -d 'Use a "stable" sum of hashes as the patch ID.  With this option: . sp'
complete -c git-patch-id -l unstable -d 'Use an "unstable" hash as the patch ID'

