# git-request-pull
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-request-pull.1.gz
complete -c git-request-pull -s p -d 'Include patch text in the output'

