# git-lfs-uninstall
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-uninstall.1.gz
complete -c git-lfs-uninstall -l local
complete -c git-lfs-uninstall -l worktree
complete -c git-lfs-uninstall -l system
complete -c git-lfs-uninstall -l skip-repo

