# git-bisect
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-bisect.1.gz
complete -c git-bisect -l no-checkout -d 'Do not checkout the new working tree at each iteration of the bisection proce…'
complete -c git-bisect -l first-parent -d 'Follow only the first parent commit upon seeing a merge commit'

