# git-prune
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-prune.1.gz
complete -c git-prune -s n -l dry-run -d 'Do not remove anything; just report what it would remove'
complete -c git-prune -s v -l verbose -d 'Report all removed objects'
complete -c git-prune -l progress -d 'Show progress'
complete -c git-prune -l expire -d 'Only expire loose objects older than <time>'

