# git-mktree
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-mktree.1.gz
complete -c git-mktree -s z -d 'Read the NUL-terminated ls-tree -z output instead'
complete -c git-mktree -l missing -d 'Allow missing objects'
complete -c git-mktree -l batch -d 'Allow building of more than one tree object before exiting'

