# git-lfs-install
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-install.1.gz
complete -c git-lfs-install -l force
complete -c git-lfs-install -l local
complete -c git-lfs-install -l worktree
complete -c git-lfs-install -l manual
complete -c git-lfs-install -l system
complete -c git-lfs-install -l skip-smudge
complete -c git-lfs-install -l skip-repo

