# git-credential-cache
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-credential-cache.1.gz
complete -c git-credential-cache -l timeout -d 'Number of seconds to cache credentials (default: 900)'
complete -c git-credential-cache -l socket -d 'Use <path> to contact a running cache daemon (or start a new cache daemon if …'

