# git-bugreport
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-bugreport.1.gz
complete -c git-bugreport -s o -l output-directory -d 'Place the resulting bug report file in <path> instead of the current directory'
complete -c git-bugreport -s s -l suffix -d 'Specify an alternate suffix for the bugreport name, to create a file named gi…'
complete -c git-bugreport -l no-diagnose -l diagnose -d 'Create a zip archive of supplemental information about the user\'s machine, Gi…'

