# git-lfs-push
# Autogenerated from man page /nix/store/x0gqngbnjah26l5cqlw17byi1c6153fv-git-lfs-3.3.0/share/man/man1/git-lfs-push.1.gz
complete -c git-lfs-push -l dry-run
complete -c git-lfs-push -l all
complete -c git-lfs-push -l object-id
complete -c git-lfs-push -l stdin

