# git-sparse-checkout
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-sparse-checkout.1.gz
complete -c git-sparse-checkout -l stdin -d 'option is provided, the directories or patterns are read from standard in as …'
complete -c git-sparse-checkout -l cone -d 'needed to be specified or core. sparseCheckoutCone needed to be enabled'
complete -c git-sparse-checkout -l no-cone -d 'is passed, the input list is considered a list of patterns'
complete -c git-sparse-checkout -l sparse-index

