# git-show-index
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-show-index.1.gz
complete -c git-show-index -l object-format -d 'Specify the given object format (hash algorithm) for the index file'

