# git-prune-packed
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-prune-packed.1.gz
complete -c git-prune-packed -s n -l dry-run -d 'Don\'t actually remove any objects, only show those that would have been remov…'
complete -c git-prune-packed -s q -l quiet -d 'Squelch the progress indicator'

