# git-pack-refs
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-pack-refs.1.gz
complete -c git-pack-refs -l all -d 'The command by default packs all tags and refs that are already packed, and l…'
complete -c git-pack-refs -l no-prune -d 'The command usually removes loose refs under $GIT_DIR/refs hierarchy after pa…'

