# git-stripspace
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-stripspace.1.gz
complete -c git-stripspace -s s -l strip-comments -d 'Skip and remove all lines starting with comment character (default #)'
complete -c git-stripspace -s c -l comment-lines -d 'Prepend comment character and blank to each line'

