# git-merge-index
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/git-merge-index.1.gz
complete -c git-merge-index -s a -d 'Run merge against all files in the index that need merging'
complete -c git-merge-index -s o -d 'Instead of stopping at the first failed merge, do all of them in one shot - c…'
complete -c git-merge-index -s q -d 'Do not complain about a failed merge program (a merge program failure usually…'

