# gitattributes
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man5/gitattributes.5.gz
complete -c gitattributes -o crlf -o text -d 'crlf=input      eol=lf End-of-line conversion While Git normally leaves file …'

