# gitcli
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man7/gitcli.7.gz
complete -c gitcli -l end-of-options -d 'for this (it also works for commands that do not distinguish between revision…'
complete -c gitcli -l option -d 'to be abbreviated only to their unique prefix (e. g'
complete -c gitcli -l opt -d 'to invoke the'
complete -c gitcli -l optimize
complete -c gitcli -s h
complete -c gitcli -l help-all
complete -c gitcli -l cached -d 'option is used to ask a command that usually works on files in the working tr…'
complete -c gitcli -l index -d 'option is used to ask a command that usually works on files in the working tr…'
complete -c gitcli -l staged -d 'is exactly like'
complete -c gitcli -l worktree -d 'is the opposite, to ask a command to work on the working tree only, not the i…'

