# gitcore-tutorial
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man7/gitcore-tutorial.7.gz
complete -c gitcore-tutorial -l - -d '+++ b/hello @@ -1 +1,2 @@  Hello World +Its a new day for git i. e'

