# gitdiffcore
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man7/gitdiffcore.7.gz
complete -c gitdiffcore -l cached -d 'flag is not used) or a "tree" object and the index file (when'
complete -c gitdiffcore -o B50/60 -d 'oc o 2. 3'
complete -c gitdiffcore -o B/60 -d 'Note that earlier implementation left a broken pair as a separate creation an…'

