# giteveryday
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man7/giteveryday.7.gz
complete -c giteveryday -o 10 -d '(to show up to 10 commits),'
complete -c giteveryday -l until

