# gitformat-signature
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man5/gitformat-signature.5.gz
complete -c gitformat-signature -l ---BEGIN -d 'Version: GnuPG v1'
complete -c gitformat-signature -l ---END -d 'oc o 2. 3'

