# gitformat-bundle
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man5/gitformat-bundle.5.gz
complete -c gitformat-bundle -l filter -d 'option in git-rev-list(1).  The resulting pack-file must be marked as a '

