# gitfaq
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man7/gitfaq.7.gz
complete -c gitfaq -l nofork -d 'option to avoid backgrounding the process'
complete -c gitfaq -l no-edit -d 'option to git commit in addition, or just save and quit when your editor opens'
complete -c gitfaq -l no-verify -d 'without being noticed (among various other ways)'

