# gitglossary
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man7/gitglossary.7.gz
complete -c gitglossary -l pickaxe-all -d 'option, it can be used to view the full changeset that introduced or removed,…'
complete -c gitglossary -l depth -d 'option to git-clone(1), and its history can be later deepened with git-fetch(…'

