# gitmodules
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man5/gitmodules.5.gz
complete -c gitmodules -l remote -d 'documentation in git-submodule(1) for details.  submodule. <name>'
complete -c gitmodules -l recurse-submodules -d 'option to git fetch and git pull.  submodule. <name>. ignore'
complete -c gitmodules -l ignore-submodules -d 'option.  The git submodule commands are not affected by this setting'

