# gitremote-helpers
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man7/gitremote-helpers.7.gz
complete -c gitremote-helpers -l export-marks -d 'in git-fast-export(1).  import-marks <file>'
complete -c gitremote-helpers -l import-marks -d 'in git-fast-export(1).  signed-tags'
complete -c gitremote-helpers -l signed-tags -d 'to git-fast-export(1).  In the absence of this capability, Git will use'

