# gitrevisions
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man7/gitrevisions.7.gz
complete -c gitrevisions -l since -d and
complete -c gitrevisions -l until -d '<refname>@{<n>}, e. g.  master@{1}'
complete -c gitrevisions -l -A---B---o---o---C---D -d 'because A and B are reachable from C, the revision range specified by these t…'

