# gitrepository-layout
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man5/gitrepository-layout.5.gz
complete -c gitrepository-layout -l depth -d 'option to git-clone(1) and git-fetch(1)'

