# gitsubmodules
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man7/gitsubmodules.7.gz
complete -c gitsubmodules -l recurse-submodules -d 'which specify whether to recurse into submodules'

