# gitweb
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/gitweb.1.gz
complete -c gitweb -l export-all -d 'option is used) allows pulling only for those repositories that have git-daem…'

