# gitweb.conf
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man5/gitweb.conf.5.gz
complete -c 'gitweb.conf' -l export-all -d '$export_auth_hook'
complete -c 'gitweb.conf' -l syntax -d 'to "highlight"'
complete -c 'gitweb.conf' -o 'S<string>' -d 'option, which refers to pickaxe entry in gitdiffcore(7) for more details)'
complete -c 'gitweb.conf' -s l -d 'option in git-ls-tree(1) manpage.  This costs a bit of I/O'
complete -c 'gitweb.conf' -l author
complete -c 'gitweb.conf' -l committer -d and
complete -c 'gitweb.conf' -l grep -d 'options in git-log(1) manpage.  Enabled by default'

