# hugo-import-jekyll
# Autogenerated from man page /nix/store/j55p74ssdv2h4c65alsn0ksv2w6x1l18-hugo-0.108.0/share/man/man1/hugo-import-jekyll.1.gz
complete -c hugo-import-jekyll -l force -d '	allow import into non-empty target directory'
complete -c hugo-import-jekyll -s h -l help -d '	help for jekyll OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-import-jekyll -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-import-jekyll -l config -d '	config file (default is path/config. yaml|json|toml)'
complete -c hugo-import-jekyll -l configDir -d '	config dir'
complete -c hugo-import-jekyll -l debug -d '	debug output'
complete -c hugo-import-jekyll -s e -l environment -d '	build environment'
complete -c hugo-import-jekyll -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-import-jekyll -l log -d '	enable Logging'
complete -c hugo-import-jekyll -l logFile -d '	log File path (if set, logging enabled automatically)'
complete -c hugo-import-jekyll -l quiet -d '	build in quiet mode'
complete -c hugo-import-jekyll -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-import-jekyll -l themesDir -d '	filesystem path to themes directory'
complete -c hugo-import-jekyll -s v -l verbose -d '	verbose output'
complete -c hugo-import-jekyll -l verboseLog -d '	verbose logging SEE ALSO'

