# hugo-convert
# Autogenerated from man page /nix/store/j55p74ssdv2h4c65alsn0ksv2w6x1l18-hugo-0.108.0/share/man/man1/hugo-convert.1.gz
complete -c hugo-convert -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-convert -s e -l environment -d '	build environment'
complete -c hugo-convert -s h -l help -d '	help for convert'
complete -c hugo-convert -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-convert -s o -l output -d '	filesystem path to write files to'
complete -c hugo-convert -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-convert -l themesDir -d '	filesystem path to themes directory'
complete -c hugo-convert -l unsafe -d '	enable less safe operations, please backup first OPTIONS INHERITED FROM PARE…'
complete -c hugo-convert -l config -d '	config file (default is path/config. yaml|json|toml)'
complete -c hugo-convert -l configDir -d '	config dir'
complete -c hugo-convert -l debug -d '	debug output'
complete -c hugo-convert -l log -d '	enable Logging'
complete -c hugo-convert -l logFile -d '	log File path (if set, logging enabled automatically)'
complete -c hugo-convert -l quiet -d '	build in quiet mode'
complete -c hugo-convert -s v -l verbose -d '	verbose output'
complete -c hugo-convert -l verboseLog -d '	verbose logging SEE ALSO'

