# hugo-mod-clean
# Autogenerated from man page /nix/store/j55p74ssdv2h4c65alsn0ksv2w6x1l18-hugo-0.108.0/share/man/man1/hugo-mod-clean.1.gz
complete -c hugo-mod-clean -l all -d '	clean entire module cache'
complete -c hugo-mod-clean -s h -l help -d '	help for clean'
complete -c hugo-mod-clean -l pattern -d '	pattern matching module paths to clean (all if not set), e. g'
complete -c hugo-mod-clean -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-mod-clean -l config -d '	config file (default is path/config. yaml|json|toml)'
complete -c hugo-mod-clean -l configDir -d '	config dir'
complete -c hugo-mod-clean -l debug -d '	debug output'
complete -c hugo-mod-clean -s e -l environment -d '	build environment'
complete -c hugo-mod-clean -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-mod-clean -l log -d '	enable Logging'
complete -c hugo-mod-clean -l logFile -d '	log File path (if set, logging enabled automatically)'
complete -c hugo-mod-clean -l quiet -d '	build in quiet mode'
complete -c hugo-mod-clean -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-mod-clean -l themesDir -d '	filesystem path to themes directory'
complete -c hugo-mod-clean -s v -l verbose -d '	verbose output'
complete -c hugo-mod-clean -l verboseLog -d '	verbose logging SEE ALSO'

