# hugo-new-site
# Autogenerated from man page /nix/store/j55p74ssdv2h4c65alsn0ksv2w6x1l18-hugo-0.108.0/share/man/man1/hugo-new-site.1.gz
complete -c hugo-new-site -l clock -d '	set the clock used by Hugo, e. g.  --clock 2021-11-06T22:30:00. 00+09:00'
complete -c hugo-new-site -s e -l environment -d '	build environment'
complete -c hugo-new-site -l force -d '	init inside non-empty directory'
complete -c hugo-new-site -s f -l format -d '	config file format'
complete -c hugo-new-site -s h -l help -d '	help for site'
complete -c hugo-new-site -l ignoreVendorPaths -d '	ignores any _vendor for module paths matching the given Glob pattern'
complete -c hugo-new-site -s s -l source -d '	filesystem path to read files relative from'
complete -c hugo-new-site -l themesDir -d '	filesystem path to themes directory OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c hugo-new-site -l config -d '	config file (default is path/config. yaml|json|toml)'
complete -c hugo-new-site -l configDir -d '	config dir'
complete -c hugo-new-site -l debug -d '	debug output'
complete -c hugo-new-site -l log -d '	enable Logging'
complete -c hugo-new-site -l logFile -d '	log File path (if set, logging enabled automatically)'
complete -c hugo-new-site -l quiet -d '	build in quiet mode'
complete -c hugo-new-site -s v -l verbose -d '	verbose output'
complete -c hugo-new-site -l verboseLog -d '	verbose logging SEE ALSO'

