# man-recode
# Autogenerated from man page /nix/store/pd1bs9asfgrpp84v8li3cr2i295w216d-man-db-2.11.1/share/man/man1/man-recode.1.gz
complete -c man-recode -s t -l to-code -d 'Convert manual pages to R encoding '
complete -c man-recode -l suffix -d 'Form each output file name by appending  suffix to the input file name, after…'
complete -c man-recode -l in-place -d 'Overwrite each input file with the output, after removing any compression ext…'
complete -c man-recode -s q -l quiet -d 'Do not issue error messages when the page cannot be converted'
complete -c man-recode -s d -l debug -d 'Print debugging information'
complete -c man-recode -s h -l help -d 'Print a help message and exit'
complete -c man-recode -s V -l version -d 'Display version information.  SEE ALSO iconv (1), man (1), manconv (1)'

