# mosh-server
# Autogenerated from man page /nix/store/wzlf72nqp8aifmhq7nz4ip5yigabwc2i-mosh-1.4.0/share/man/man1/mosh-server.1.gz
complete -c mosh-server -s s -d 'bind to the local interface used for an incoming SSH connection, given in the…'
complete -c mosh-server -s v -d 'Print some debugging information even after detaching'
complete -c mosh-server -s i -d 'IP address of the local interface to bind (for multihomed hosts)'
complete -c mosh-server -s p -d 'UDP port number or port-range to bind'
complete -c mosh-server -s c -d 'Number of colors to advertise to applications through TERM (e. g.  8, 256)'
complete -c mosh-server -s l -d 'Locale-related environment variable to try as part of a fallback environment,…'

