# scalar
# Autogenerated from man page /nix/store/g456faq9v8zmsi3995fj7lsibjibwvz6-git-2.38.1/share/man/man1/scalar.1.gz
complete -c scalar -s C
complete -c scalar -s c
complete -c scalar -l full-clone -d 'git sparse-checkout set to expand the set of directories you want to see, or …'
complete -c scalar -s b -l branch
complete -c scalar -l single-branch

