# yank
# Autogenerated from man page /nix/store/xwjrk214g0gnq55vnbacvw0kpjgifc9f-yank-1.3.0/share/man/man1/yank.1.gz
complete -c yank -s 1 -d 'If only one field is recognized, select it and invoke command without display…'
complete -c yank -s d -d 'All input characters not present in delim will be recognized as fields, see D…'
complete -c yank -s g -d 'Use pattern to recognize fields, expressed as a POSIX extended regular expres…'
complete -c yank -s i -d 'Ignore case differences between pattern and the input'
complete -c yank -s l -d 'Use the default delimiters except for space, see DELIMITERS'
complete -c yank -s v -d 'Prints version'
complete -c yank -s x -d 'Use alternate screen'

