# zoxide-remove
# Autogenerated from man page /nix/store/qf3sp6yqccvj3vrscjf66q59aw4sr0cz-zoxide-0.8.3/share/man/man1/zoxide-remove.1.gz
complete -c zoxide-remove -s h -l help -d 'Print help information'
complete -c zoxide-remove -s i -l interactive -d 'Use interactive selection.  This option requires fzf(1)'

