# zoxide-init
# Autogenerated from man page /nix/store/qf3sp6yqccvj3vrscjf66q59aw4sr0cz-zoxide-0.8.3/share/man/man1/zoxide-init.1.gz
complete -c zoxide-init -l cmd -d 'Changes the prefix of the z and zi commands'
complete -c zoxide-init -s h -l help -d 'Print help information'
complete -c zoxide-init -l hook -d 'Changes how often zoxide increments a directory\'s score: . TS tab(|); l l'
complete -c zoxide-init -l no-cmd -d 'Prevents zoxide from defining the z and zi commands'

