# zsoelim
# Autogenerated from man page /nix/store/pd1bs9asfgrpp84v8li3cr2i295w216d-man-db-2.11.1/share/man/man1/zsoelim.1.gz
complete -c zsoelim -s C -l compatible -d 'This flag is available for compatibility with other  soelim programs'
complete -c zsoelim -s h -l help -d 'Print a help message and exit'
complete -c zsoelim -s V -l version -d 'Display version information'

